apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/biswajit134/Chat-app-DevOps.git
    targetRevision: main
    path: k8s_demo


  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      
  destination:
    server: https://kubernetes.default.svc
    namespace: chat-app