apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatapp-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/biswajit134/Chat-app-DevOps.git
    targetRevision: main
    path: chatapp_helm/chatapp-frontend
    helm:
      releaseName: chatapp-frontend

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      
  destination:
    server: https://kubernetes.default.svc
    namespace: chat-app