apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  jwt-secret: OTFmZmY0ODlmYjBlOTM2MmM2MDliMWQzM2I5NGFkM2VkMjBlNGM1N2VhYzU5NWMwODFhOWZmYzEwMDEzYTFjOA==